= Exception

`Xtuple\Util\Exception` package provides a set of classes to throw translatable exceptions.

`Xtuple\Util\Exception\Throwable` is the base interface for all exceptions,
and `Xtuple\Util\Exception\AbstractThrowable` is the base abstract class for all the exceptions.
Unlike other packages,
this package is not using decorators for abstract classes.
Instead, `Xtuple\Util\Exception\AbstractThrowable` extends `\Exception`
to utilize the default implementation of the `\Throwable` interface
(3rd party PHP code usually catches `\Exception`, not `\Throwable`).
All the implementations of `Xtuple\Util\Exception\AbstractThrowable` represent different shortcuts of its constructor.

`Xtuple\Util\Exception\Throwable` provides three methods:

* `message(): \Xtuple\Util\Type\String\Message\Message\Message` - translatable exception message.
* `exceptions(): \Xtuple\Util\Exception\Collection\Sequence\ListThrowable` - list of all previous exceptions,
starting with the original exception.
* `errors(): \Xtuple\Util\Type\String\Message\Message\Collection\Sequence\ListMessage` - list of error messages,
collection for the exception.
This allows to throw one "final" exception for all occurred issues
(e.g. all errors from multiple async HTTP requests).

`Xtuple\Util\Exception\AbstractThrowable` provides final implementations for all these methods,
and also overrides the default `__toString()`,
to return information about all previous exceptions
and all error messages inside them,
instead of the stack trace for the exception.

== Exception

`Xtuple\Util\Exception\ExceptionWithMessage` is a default implementation of `Xtuple\Util\Exception\AbstractThrowable`,
without any constructor customizations.
It may be especially helpful,
when all the parameters are already provided in the required types.

[source]
----
use Xtuple\Util\Exception\ExceptionWithMessage;
use Xtuple\Util\Type\String\Message\Argument\Collection\Set\ArraySetArgument;
use Xtuple\Util\Type\String\Message\Message\MessageStruct;
use Xtuple\Util\Type\String\Message\Type\Number\Integer\IntegerArgument;
use Xtuple\Util\Type\String\Message\Type\String\StringArgument;

// $message might be returned from HTTP client
$message = new MessageStruct('HTTP error {code}: {message}', new ArraySetArgument([
  new IntegerArgument('code', 404),
  new StringArgument('message', 'Page not found'),
]));

throw new ExceptionWithMessage($message);
----

`Xtuple\Util\Exception\ExceptionWithArguments` is a shortcut for `Xtuple\Util\Exception\ExceptionWithMessage`,
that encapsulates `Xtuple\Util\Type\String\Message\Message\MessageStruct`.
It's useful when non-string arguments are required.

[source]
----
use Xtuple\Util\Exception\ExceptionWithArguments;
use Xtuple\Util\Type\String\Message\Argument\Collection\Set\ArraySetArgument;
use Xtuple\Util\Type\String\Message\Type\Number\Integer\IntegerArgument;
use Xtuple\Util\Type\String\Message\Type\String\StringArgument;

throw new ExceptionWithMessage('HTTP error {code}: {message}', new ArraySetArgument([
  new IntegerArgument('code', 404),
  new StringArgument('message', 'Page not found'),
]));
----

`Xtuple\Util\Exception\Exception` is a shortcut for `Xtuple\Util\Exception\ExceptionWithMessage`,
that encapsulates `Xtuple\Util\Type\String\Message\Message\MessageWithTokens`
(as it's the most commonly used variant and requires the simplest form).
All passed parameters are treated as string arguments
(by `Xtuple\Util\Type\String\Message\Message\MessageWithTokens`).

[source]
----
use Xtuple\Util\Exception\Exception;

throw new Exception('HTTP error {code}: {message}', [
  'code' => 404, // this parameter would be cast to string and can't be localized as an integer later
  'message' => 'Page not found',
]));
----

== ChainException

`Xtuple\Util\Exception\ChainException` is a shortcut for `Xtuple\Util\Exception\Exception`
when a previous exception should be re-thrown.

[source]
----
use Xtuple\Util\Exception\ChainException;
use Xtuple\Util\Exception\Exception;

try {
  throw new Exception('HTTP error {code}: {message}', [
    'code' => 404,
    'message' => 'Page not found',
  ]));
}
catch (\Throwable $e) {
  throw new ChainException($e, 'API request {request} failed', [
    'request' => 'api/v2/address',
  ]);
}
----

== MultiErrorException

`Xtuple\Util\Exception\MultiErrorException` is a shortcut for `Xtuple\Util\Exception\Exception`
when an exception with multiple errors should be thrown.

[source]
----
use Xtuple\Util\Exception\MultiErrorException;
use Xtuple\Util\Type\String\Message\Type\String\StringMessage;

// See https://secure.php.net/manual/en/function.curl-multi-strerror.php
$ch1 = curl_init('http://example.com/');
$ch2 = curl_init('http://php.net/');
$mh = curl_multi_init();
curl_multi_add_handle($mh, $ch1);
curl_multi_add_handle($mh, $ch2);
$errors = [];
do {
  $status = curl_multi_exec($mh, $active);
  if ($status > 0) {
    $errors[] = new StringMessage(curl_multi_strerror($status));
  }
} while ($status === CURLM_CALL_MULTI_PERFORM || $active);

if (!empty($errors)) {
  // Allow to log/process all occured errors, instead of throwing an exception after the first one has occured.
  throw new MultiErrorException($errors, 'HTTP requests failed');
}
----
